### ISSUE TITLE
Unit test/lint result linking

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/duti#10]
It would be awesome if unit test and lint results which have file paths in them could be formatted as links right to those files

**Comment by daedalus28** [comment]
Here's an example from jest

https://github.com/facebook/jest/blob/79cbda4e1fc4b1fa293a03794611ec072baf69fa/dangerfile.js#L19-L26

**Comment by sean-clayton** [comment]
Right now my implementation has this as the url: `https://github.com/smartprocure/duti/blob/feature/LinkifyResults/circleci/project/src/duties/lint.spec.js`

What kinda sucks is that it's hard to detect what is the project's folder--any ideas on how this can work on any and all CI systems? If I made this CircleCI-specific it's easy, but I'm not sure if we want to do that.

**Comment by daedalus28** [comment]
We could make it a config option

**Comment by sean-clayton** [comment]
Closed by #52
