### ISSUE TITLE
Add some robot personality

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/duti#42]
When autofixing a PR, if the diff is > some threshold, add an image like this to the comment:

![kill all humans](https://media.licdn.com/mpr/mpr/shrinknp_800_800/p/2/005/0b3/059/36a09a3.jpg)

**Comment by daedalus28** [comment]
Also, this is issue #42!

**Comment by sean-clayton** [comment]
:+1::robot:

**Comment by sean-clayton** [comment]
@daedalus28 what should the threshold be for this to trigger?

**Comment by daedalus28** [comment]
the 500 you picked is probably fine
